config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'
  devise_for :users 

  resources :activities
  resources :users
  resources :favors
  get 'ask-favor' => 'favors#new'
  get 'publish-favor' => 'favors#new'

  resources :favor_requests, except: [:index, :show, :new]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  firstname              :string
#  lastname               :string
#  home_town              :string
#  languages              :string
#  phone                  :integer
#  bio                    :text
#  points                 :integer
#  skills                 :string
#  admin                  :boolean
#  image                  :string
#  username               :string
#  name                   :string
#  latitude               :float
#  longitude              :float
#  address                :string
#

class User < ActiveRecord::Base
  attr_accessor :login
  before_create :set_user_full_name

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :favors_asked, class_name: 'Favor', foreign_key: 'favor_to' 
  has_many :favors_done, class_name: 'Favor', foreign_key: 'favor_from'

  has_many :favor_requests
  has_many :activities

  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

  private

  def set_user_full_name
    self.name = "#{firstname}" + " " + "#{lastname}"
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end





end

app/controllers/user/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_favours.html.erb
<% current_user.favors.each do |fr| %>
  <%= fr.place %>
  <%= fr.description %>
<% end %>

<%= current_user.id %>

app/views/users/show.html.erb
<h1>User info</h1>

<%= image_tag @user.image.url(:thumb) %>
<p>First name: <%= @user.firstname %></p>
<p>Last name: <%= @user.lastname %></p>
<p>Email: <%= @user.email %></p>
<p>Member since: <%= @user.created_at %></p>
<p>Hometown: <%= @user.home_town %></p>
<p>Current location: <%= @location %></p>

<h3>Asked Favors</h3>
<% @user.favors_asked.each do |fr| %>
  <%= link_to fr.description, favor_path(fr) %><br />
<% end %>


<h3>Published Favors</h3>
<% present @user do |p| %>
  <%= p.published_uncompleted_favors.join(", ").html_safe %><br />

  <h3>Done Favors<h3>

<% end %>